### ISSUE TITLE
Build  this interface 

### ISSUE THREAD

**Issue by ayush-raj8** [UAceIt-Winter-of-Mentorship/Krishi-Lens#1]
Description 
->At the top , Krishi Lens should be there.'
-> 5 rectangular sections for Rice, Paddy, Corn, Cassava  and About . (instead of 'me', 'us' in the picture). Each section must have icon and name.
 
Something like this in picture shown below... 
<img width="99" alt="image" src="https://user-images.githubusercontent.com/52033949/149312527-cb1d82ad-cbbe-445f-b0ad-1b2888b469e0.png">

It will be served on first serve basis.

**Comment by TheArushiSingh** [comment]
you may assign it to me! I can do this.
